'use client'

import { useState } from 'react'
import { TriangleAlert } from 'lucide-react'
import { useNetChaos } from '@/hooks/use-netchaos'
import { useToast } from '@/components/ui/toast'
import { Sidebar } from '@/components/netchaos/sidebar'
import { TopHeader } from '@/components/netchaos/top-header'
import { StatusCards } from '@/components/netchaos/status-cards'
import { ChaosConfigPanel } from '@/components/netchaos/chaos-config-panel'
import { CurrentConfigCard } from '@/components/netchaos/current-config-card'
import { ActivityPanel } from '@/components/netchaos/activity-panel'
import { SettingsView } from '@/components/netchaos/settings-view'
import { ConnectionBadge } from '@/components/netchaos/connection-badge'
import type { NavView } from '@/components/netchaos/nav'

function SectionHeading({ title, description }: { title: string; description: string }) {
  return (
    <div className="space-y-1">
      <h2 className="text-sm font-semibold tracking-tight">{title}</h2>
      <p className="text-sm text-muted-foreground">{description}</p>
    </div>
  )
}

export function Dashboard() {
  const nc = useNetChaos()
  const { toast } = useToast()
  const [view, setView] = useState<NavView>('overview')
  const [sidebarOpen, setSidebarOpen] = useState(false)

  const handleApply = async () => {
    const result = await nc.apply()
    if (result?.ok) {
      toast({ title: 'Chaos configuration updated', tone: 'success' })
    } else {
      toast({
        title: 'Failed to apply configuration',
        description: result?.error,
        tone: 'error',
      })
    }
  }

  return (
    <div className="flex min-h-svh bg-background">
      <Sidebar
        active={view}
        onNavigate={setView}
        health={nc.health}
        open={sidebarOpen}
        onClose={() => setSidebarOpen(false)}
      />

      <div className="flex min-w-0 flex-1 flex-col">
        <TopHeader
          health={nc.health}
          onRefresh={nc.refresh}
          refreshing={nc.loading}
          onOpenSidebar={() => setSidebarOpen(true)}
        />

        <main className="mx-auto w-full max-w-6xl flex-1 space-y-6 px-4 py-6 md:px-6">
          {nc.loadError && (
            <div className="flex items-start gap-3 rounded-lg border border-destructive/40 bg-destructive/10 p-4">
              <TriangleAlert className="mt-0.5 size-4 shrink-0 text-destructive" />
              <div className="space-y-0.5">
                <p className="text-sm font-medium text-destructive">
                  Unable to reach the NetChaos backend
                </p>
                <p className="text-xs text-muted-foreground">{nc.loadError}</p>
              </div>
            </div>
          )}

          {view === 'overview' && (
            <>
              <StatusCards health={nc.health} config={nc.config} />
              <div className="grid gap-6 lg:grid-cols-3">
                <div className="lg:col-span-1">
                  <CurrentConfigCard config={nc.config} />
                </div>
                <ActivityPanel
                  activity={nc.activity}
                  limit={8}
                  className="h-full lg:col-span-2"
                />
              </div>
            </>
          )}

          {view === 'controls' && (
            <div className="grid gap-6 lg:grid-cols-3">
              <div className="lg:col-span-2">
                <ChaosConfigPanel
                  draft={nc.draft}
                  applying={nc.applying}
                  dirty={nc.dirty}
                  onChange={nc.updateDraft}
                  onApply={handleApply}
                  onReset={nc.resetDraft}
                />
              </div>
              <div className="space-y-6 lg:col-span-1">
                <CurrentConfigCard config={nc.config} />
              </div>
            </div>
          )}

          {view === 'activity' && (
            <>
              <SectionHeading
                title="Activity"
                description="Client-side events generated by dashboard actions and health checks."
              />
              <ActivityPanel activity={nc.activity} className="h-[70svh]" />
            </>
          )}

          {view === 'settings' && (
            <>
              <div className="flex items-center justify-between">
                <SectionHeading
                  title="Settings"
                  description="Connection and proxy topology for this NetChaos instance."
                />
                <ConnectionBadge health={nc.health} />
              </div>
              <SettingsView rootStatus={nc.rootStatus} health={nc.health} />
            </>
          )}
        </main>
      </div>
    </div>
  )
}
